// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPFjXIJ6c3j3IiGK5jQKbqJkh2cKznz1w',
    appId: '1:409494602789:web:94b008e1517978e5752bcc',
    messagingSenderId: '409494602789',
    projectId: 'chat-app-f6bdf',
    authDomain: 'chat-app-f6bdf.firebaseapp.com',
    storageBucket: 'chat-app-f6bdf.firebasestorage.app',
    measurementId: 'G-6E72JY4PPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu95rBMlCngRM4dYD_slvLfcF4mtwXIn0',
    appId: '1:409494602789:android:777a4ba8d043dd1b752bcc',
    messagingSenderId: '409494602789',
    projectId: 'chat-app-f6bdf',
    storageBucket: 'chat-app-f6bdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoDaA3EUBKuW1QJ0Wa1Mfh5N9dsAYUbUE',
    appId: '1:409494602789:ios:7d7ecdf12a5218d3752bcc',
    messagingSenderId: '409494602789',
    projectId: 'chat-app-f6bdf',
    storageBucket: 'chat-app-f6bdf.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoDaA3EUBKuW1QJ0Wa1Mfh5N9dsAYUbUE',
    appId: '1:409494602789:ios:7d7ecdf12a5218d3752bcc',
    messagingSenderId: '409494602789',
    projectId: 'chat-app-f6bdf',
    storageBucket: 'chat-app-f6bdf.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPFjXIJ6c3j3IiGK5jQKbqJkh2cKznz1w',
    appId: '1:409494602789:web:fe574a66d463447e752bcc',
    messagingSenderId: '409494602789',
    projectId: 'chat-app-f6bdf',
    authDomain: 'chat-app-f6bdf.firebaseapp.com',
    storageBucket: 'chat-app-f6bdf.firebasestorage.app',
    measurementId: 'G-CX8NPH3GRH',
  );
}